### ISSUE TITLE
Missing: From tensorflow model to json model file

### ISSUE THREAD

**Issue by tim-peters** [tensorflow/magenta-demos#33]
Especially for beginners it would be very helpful if you could describe the step from a pre-trained model from tensorflow (which is e.g. described in the [magenta/sketch-rnn readme](https://github.com/tensorflow/magenta/tree/master/magenta/models/sketch_rnn)) to the json-model-file (which is downloaded from the google storage in the readme of your **Sketch-RNN-JS** example).

This would enable people to try out your example with their own models.

Update:
- I've found the [Tensorflow-JS-Converter](https://github.com/tensorflow/tfjs-converter) which seems to create the needed model from a `SavedModel`-File. Unfortunately `sketch_rnn_train` saves the model in checkpoint format which tfjs-converter is unable to handle.

**Comment by chrislos** [comment]
hey tim have you found any solutions? I'm stuck at the pretty exact same position.
Quite difficult to figure out how to do this right.

all the best
c.

**Comment by tim-peters** [comment]
unfortunately not :( I even managed to get in touch with the research lead of Googles brain team about it. But the only thing I found out is that sketch-rnn will probably get refactored around the new tensorflow.js and magenta.js interfaces.
For our project this will be too late so sadly we had to find ways around sketch-rnn..

**Comment by hardmaru** [comment]
Hi @tim-peters 

A newer version of sketch-rnn will be built with tensorflow.js and I'll be sure to include step-by-step instructions (possibly with a colab notebook) on how to train a custom dataset using the TensorFlow version, and export that into a JSON format that will work with the web version.

Due to various projects and ongoing priorities, I won't be able to commit to any timing though.

Cheers.

**Comment by hardmaru** [comment]
@tim-peters @chrislos Are you using sketch-rnn for the full encoder or decoder, or just the decoder version only (for auto-complete)? I can try to dig up the code that does the conversion and get something working for you.

**Comment by chrislos** [comment]
Dear hardmaru,

thanks for your response! Unfortunately my case is a little bit different than @tim-peters. 

I'm desperately try to port a midi composition of mine encoded into a magenta performance rnn (performance_with_dynamics.mag) bundle into readable tensorflow js json format.


I'm stuck at the point where I have to use checkpoint_converter.py with a model.ckpt file. 
the files I have so far is one *.mag bundle file I created via performance_rnn_generate function and several model.cpkt triplets (index, meta, data) located the training folder.

My checkpoint_converter seems not to accept those cpkt files or I just don't know which is the correct input the script needs.

my last error message out of terminal was:
" tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /Users/chris/Desktop/AI/checkpoints/model.cpkt "

maybe you could give me a hint how to transform a magenta bundle into correct tensorflow js json files?

thanks so much an all the best 
christian

**Comment by cghawthorne** [comment]
@chrislos I think your issue is separate from the one @tim-peters is talking about and is unrelated to sketch-rnn. Can you open a new bug with details about which javascript setup you're trying to export checkpoints for?

**Comment by hardmaru** [comment]
Hi @tim-peters (cc @cghawthorne @douglaseck):

I've created a self-contained tutorial in the form of a short IPython notebook that will convert a TensorFlow model (in my case, a TF sketch-rnn model trained on the Kanji dataset) into a `custom.gen.json` model that can be used for `sketch-rnn-js`. In the future versions when we write the tensorflow.js versions of sketch-rnn I will also be sticking to the same file format.

Here is the link to the tutorial in my fork:

https://github.com/hardmaru/magenta-demos/blob/master/jupyter-notebooks/Sketch_RNN_TF_To_JS_Tutorial.ipynb

It is in the process of being merged back into the main branch.

Cheers.

**Comment by hardmaru** [comment]
Hi @tim-peters 

This tutorial is now merged:

https://github.com/tensorflow/magenta-demos/blob/master/jupyter-notebooks/Sketch_RNN_TF_To_JS_Tutorial.ipynb

This should help you train a model using the [TensorFlow](https://github.com/tensorflow/magenta/tree/master/magenta/models/sketch_rnn) version of sketch-rnn and deploy the model using [sketch-rnn-js](https://github.com/tensorflow/magenta-demos/tree/master/sketch-rnn-js).

If you have any issues using this please feel free to contact me.
