### ISSUE TITLE
[bug] - tensorflow/magenta-demos - AI piano doesn't work OOB (tmm2018)

### ISSUE THREAD

**Issue by tmm2018** [tensorflow/magenta-demos#39]
### [bug] - tensorflow/magenta-demos - AI piano doesn't work OOB (tmm2018)

**when trying to run ai-duet (the accompanmient thing):**
- <sub>*it compiles*</sub></sub>

---

**however, when i get to run it in macos high sierra on macbook a1278 with core i5:**
- <sub>*i open the default localhost path*</sub>
- <sub>*it doesn't display anything at all*</sub>
- <sub>*it reports some sort of error on terminal*</sub>

```
* Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [12/Jun/2018 12:18:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Jun/2018 12:18:52] "GET /build/Main.js HTTP/1.1" 404 -
127.0.0.1 - - [12/Jun/2018 12:18:52] "GET /images/AIDuet_32.png HTTP/1.1" 200 -
```

**Comment by adarob** [comment]
We are no longer supporting AI Duet in this repo. Please see the main repo: https://github.com/googlecreativelab/aiexperiments-ai-duet
