### ISSUE TITLE
AttributeError: 'module' object has no attribute 'download_bundle'

### ISSUE THREAD

**Issue by iphyer** [tensorflow/magenta-demos#4]
Hi, I have tried your model but I have found that altough, I have install magenta right and put the performance_with_dynamics.mag file in the right directory, I still enconter this error:
 
     `---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-11-3eb1b89367f7> in <module>()
      1 dir(mm)
      ----> 2 mm.notebook_utils.download_bundle(BUNDLE_NAME, BUNDLE_DIR)
      3 bundle = mm.sequence_generator_bundle.read_bundle_file(os.path.join(BUNDLE_DIR, BUNDLE_NAME))
      4 generator_map = performance_sequence_generator.get_generator_map()
      5 generator = generator_map[MODEL_NAME](checkpoint=None, bundle=bundle)

       AttributeError: 'module' object has no attribute 'download_bundle'

**Comment by dbl001** [comment]
Same issue:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-2-043f7a0ca417> in <module>()
----> 1 mm.notebook_utils.download_bundle(BUNDLE_NAME, BUNDLE_DIR)
      2 bundle = mm.sequence_generator_bundle.read_bundle_file(os.path.join(BUNDLE_DIR, BUNDLE_NAME))
      3 generator_map = performance_sequence_generator.get_generator_map()
      4 generator = generator_map[MODEL_NAME](checkpoint=None, bundle=bundle)
      5 generator.initialize()

AttributeError: 'module' object has no attribute 'download_bundle'
```

**Comment by cghawthorne** [comment]
I think this may have been because our pip package was out of date. Can you try upgrading to the latest version and try again?
