### ISSUE TITLE
performance_rnn midi timing broken?

### ISSUE THREAD

**Issue by robinmeier** [tensorflow/magenta-demos#43]
hi,

i've recorded the audio output of performance_rnn (browser) in parallel to the midi output and the two are not aligned.

midi is usually ahead, but sometimes lagging behind. the delay is not constant.

i haven't managed to test with the offline version of performance_rnn because my OS is too old (?). but am wondering if it is possible to fix the variable delay in the online version.

cheers

used Chrome and MaxMSP os MacOS 10.10.5 routing audio with Soundflower

**Comment by cghawthorne** [comment]
Is this for the TensorFlow.js demo? https://goo.gl/magenta/performancernn-demo

I'm not surprised that there's some amount of delay given what we're doing with Tone.js/webaudio and that the inference is happening in the same thread that's managing the UI and the audio output. If you're using the MIDI output to create audio, I'd definitely recommend just muting the tab.

If you want to generate music offline, you can also check out our colab implementation: https://colab.research.google.com/notebook#fileId=/v2/external/notebooks/magenta/performance_rnn/performance_rnn.ipynb
