### ISSUE TITLE
piano-genie build doesn't seem to work

### ISSUE THREAD

**Issue by notwaldorf** [tensorflow/magenta-demos#57]
I just cloned the piano-genie demo and tried to build it, but `yarn build` gives me this error:
```
TypeScript error: node_modules/@tensorflow/tfjs-core/dist/kernels/webgl/gpgpu_context.d.ts(15,27): Error TS2304: Cannot find name 'WebGLLoseContext'.
error Command failed with exit code 1.
```

Is there a problem with the version of tfjs it's using?

cc @chrisdonahue

**Comment by chrisdonahue** [comment]
Just tried and got the same issue. Fixed it by upgrading to `@tensorflow/tfjs@0.13.4` and `@tensorflow/tfjs-core@0.13.11`. Confirmed that tests still work after upgrade.

**Comment by chrisdonahue** [comment]
Hey just an FYI that I am working on a PR to add a stripped-down version of Piano Genie directly to magenta-js. Hope to have it in by EOD.

**Comment by chrisdonahue** [comment]
This can be closed now probably :)
