### ISSUE TITLE
Are you planning on making a version for Logic Pro X?

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/magenta-demos#67]
Are you planning on making a version of Magenta Studio plugins for Logic Pro X?

I personally don't use Ableton.

https://magenta.tensorflow.org/studio

Here's how you make a audio unit in Logic Pro X:
https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/AudioUnit.html#//apple_ref/doc/uid/TP40014214-CH22-SW1

**Comment by adarob** [comment]
Sorry, but we don't have any plans for this, as it would be non-trivial. You can use the standalone versions however.
