### ISSUE TITLE
Python way of loading model

### ISSUE THREAD

**Issue by nitish11** [tensorflow/magenta-demos#69]
What is the python code for loading the model?

For [reference ](https://github.com/tensorflow/magenta-demos/tree/master/sketch-rnn-js#sketch-rnn), what is the way to load a JSON model file in python?

**Comment by adarob** [comment]
The Python code is here: https://github.com/tensorflow/magenta/tree/master/magenta/models/sketch_rnn

**Comment by nitish11** [comment]
@adarob : the question is how to load **JSON model** in python. 

Javascript code : 

'''
var model_data = Parsed_JSON_file_of_pretrained_weights();
var model = new SketchRNN(model_data); // this creates your model using the pre-trained weights inside model_data
'''

In the [python code](https://github.com/tensorflow/magenta/tree/master/magenta/models/sketch_rnn#pre-trained-models) , the pre-trained-models are not in JSON format. 

Actually, I want to use pre-trained model for chair in python code and the chair model is in JSON format.

**Comment by adarob** [comment]
I don't think you can load a JSON model in Python. @hardmaru is there a chair model for Python?

**Comment by nitish11** [comment]
I found the answer for the other way round, i.e, converting a python model into JSON file, recording it for future reference.

https://github.com/tensorflow/tfjs-converter

https://github.com/tensorflow/magenta-demos/issues/33
